accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
path('login/', auth_views.LoginView.as_view(), name='login'),
]

fifaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('player_search/', include('player_search.urls')),
     path('accounts/', include('accounts.urls')),
     path('team_chemistry/', include('team_chemistry.urls')),
]

player_search/urls.py
from django.urls import path
from . import views

app_name = 'player_search'

urlpatterns = [
    
    path('', views.search_player, name='search_player'),
    path('add_player/<int:player_id>/', views.add_player, name='add_player'),  # Notice the addition of the player_id argument
    path('show_players/', views.show_players, name='show_players'),
    path('api/players/data/', views.get_all_data, name='get-all-data'),

   

]

player_search/models.py
from django.db import models
from django.contrib.auth.models import User

class League(models.Model):
    league_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Nation(models.Model):
    nation_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Club(models.Model):
    club_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=100)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

class Player(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    rating = models.IntegerField()
    position = models.CharField(max_length=50)
    nation = models.ForeignKey(Nation, on_delete=models.SET_NULL, null=True, blank=True)
    club = models.ForeignKey(Club, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.name

player_search/forms.py
from django import forms

class PlayerSearchForm(forms.Form):
    player_name = forms.CharField(label='Player Name', max_length=100)
    player_rating = forms.IntegerField(label='Player Rating')

player_search/views.py
import requests
from django.shortcuts import render, redirect
from .forms import PlayerSearchForm
from .models import Player, Nation, Club, League
from django.contrib import messages
from .serializers import PlayerSerializer
from django.http import JsonResponse
from collections import defaultdict



 # from futdb documentation

def search_player(request):
    form = PlayerSearchForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        player_name = form.cleaned_data['player_name']
        player_rating = form.cleaned_data['player_rating']

        api_url = 'https://futdb.app/api/players/search'
        auth_token = 'aa1bc882-5c89-467e-bee1-b7d1e1be8382'
        request_body = {'name': player_name, 'rating': player_rating}

        try:
            response = requests.post(api_url, json=request_body, headers={'X-AUTH-TOKEN': auth_token})
            response.raise_for_status()  
            data = response.json()

            players = data.get('items', [])

            # Save the players in the session 
            request.session['search_results'] = players

            return render(request, 'player_search/results.html', {'players': players, 'form': form})

        except requests.exceptions.RequestException as e:
            return render(request, 'player_search/search.html', {'form': form, 'error_message': str(e)})

    return render(request, 'player_search/search.html', {'form': form})


import requests

def add_player(request, player_id):
    # Get the search results
    players = request.session.get('search_results')
    selected_player = next((p for p in players if p['id'] == player_id), None)

    if not selected_player:
        messages.error(request, "Couldn't find the selected player.")
        return redirect('player_search:search_player')

    
    api_base = 'https://futdb.app/api/'
    headers = {'X-AUTH-TOKEN': 'aa1bc882-5c89-467e-bee1-b7d1e1be8382'}

    # Fetch Nation, Club, and League information
    try:
        nation_response = requests.get(f"{api_base}nations/{selected_player['nation']}", headers=headers)
        nation_response.raise_for_status()
        nation_data = nation_response.json()
        print(f"Nation Data: {nation_data}") 

        club_response = requests.get(f"{api_base}clubs/{selected_player['club']}", headers=headers)
        club_response.raise_for_status()
        club_data = club_response.json()

        league_response = requests.get(f"{api_base}leagues/{selected_player['league']}", headers=headers)
        league_response.raise_for_status()
        league_data = league_response.json()

    except requests.exceptions.RequestException as e:
        messages.error(request, f"Error fetching additional player data: {e}")
        return redirect('player_search:search_player')

    # Store to database
    nation_obj, _ = Nation.objects.get_or_create(nation_id=nation_data['nation']['id'], defaults={'name': nation_data['nation']['name']})
    league_obj, _ = League.objects.get_or_create(league_id=league_data['league']['id'], defaults={'name': league_data['league']['name']})
    club_obj, _ = Club.objects.get_or_create(club_id=club_data['club']['id'], defaults={'name': club_data['club']['name'], 'league': league_obj})

    Player.objects.create(
        user=request.user,
        name=selected_player['name'],
        rating=selected_player['rating'],
        position=selected_player['position'],
        nation=nation_obj,
        club=club_obj
        
    )

    messages.success(request, 'Player added successfully!')
    return redirect('player_search:search_player')


def show_players(request):
    # Get the currently logged-in user
    user = request.user

    # Retrieve players associated with the logged-in user
    players = Player.objects.filter(user=user)

    return render(request, 'player_search/show_players.html', {'players': players})




def get_all_data(request):
    if not request.user.is_authenticated:
        return JsonResponse({"error": "User not authenticated"})

    user = request.user.id
    players = Player.objects.filter(user=user).order_by('-rating')

# a dictionairy data is made with two keys: leagues, which each contain dictionaries for clubs, and clubs which have the players
    data = {
        "leagues": defaultdict(lambda: {
            "clubs": defaultdict(list)
        }),
        "nations": defaultdict(list),
    }

    for player in players:
        data["leagues"][player.club.league.name]["clubs"][player.club.name].append(PlayerSerializer(player).data)
        data["nations"][player.nation.name].append(PlayerSerializer(player).data)

    return JsonResponse(data)

player_search/templates/player_search/results.html
<!DOCTYPE html>
<html>
<head>
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>

    <!-- Display messages to the user -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <table>
        <tr>
            <th>Name</th>
            <th>Rating</th>
            <th>Position</th>
            <th>Nation</th>
            <th>Club</th>
            <th>League</th>
            <th>Action</th>
        </tr>
        {% for player in players %}
        <tr>
            <td>{{ player.name }}</td>
            <td>{{ player.rating }}</td>
            <td>{{ player.position }}</td>
            <td>{{ player.nation }}</td>
            <td>{{ player.club }}</td>
            <td>{{ player.league }}</td>
            <!-- "Add Player" button -->
            <td><a href="{% url 'player_search:add_player' player.id %}">Add Player</a></td>
        </tr>
        {% endfor %}
    </table>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</body>
</html>

player_search/templates/player_search/search.html
<!DOCTYPE html>
<html>
<head>
  <title>FIFA Player Search</title>
</head>
<body>
  <h1>FIFA Player Search</h1>
  <a href="{% url 'player_search:show_players' %}">Show Players</a>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Search</button>
  </form>
  {% if players %}
  <form method="post" action="{% url 'player_search:add_player' %}">
    {% csrf_token %}
    <input type="hidden" name="player_name" value="{{ form.cleaned_data.player_name }}">
    <input type="hidden" name="player_rating" value="{{ form.cleaned_data.player_rating }}">
    <button type="submit">Add Player</button>
  </form>
  {% endif %}

</body>
</html>

player_search/templates/player_search/show_players.html
<!DOCTYPE html>
<html>
<head>
    <title>Show Players</title>
</head>
<body>
    <h1>Show Players</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Rating</th>
            <th>Position</th>
            <th>Nation</th>
            <th>Club</th>
            <th>League</th>
        </tr>
        {% for player in players %}
        <tr>
            <td>{{ player.name }}</td>
            <td>{{ player.rating }}</td>
            <td>{{ player.position }}</td>
            <td>{{ player.nation.name }}</td>
            <td>{{ player.club.name }}</td>
            <td>{{ player.club.league.name }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>